In [1]:
import pickle
import pandas as pd

from scipy.stats import ttest_rel

In [2]:
male_profiles = [i for i in range(528)]
female_profiles = [i+528 for i in male_profiles]

In [3]:
# combine all sentiment classifiers in one dataframe

with open("data/analysis/gpt-4o-mini_given_robust.pkl", "rb") as f:
    df_gpt_robust = pickle.load(f)
with open("data/analysis/gpt-4o-mini_given_siebert.pkl", "rb") as f:
    df_gpt_siebert = pickle.load(f)
with open("data/analysis/gpt-4o-mini_given_bert-base-multilingual.pkl", "rb") as f:
    df_gpt_bert_base = pickle.load(f)
df_gpt = df_gpt_robust.join(df_gpt_siebert['siebert']).join(df_gpt_bert_base['bert-base'])
df_gpt['siebert'] = df_gpt['siebert'].apply(lambda x: x[0]['label'])

with open("data/analysis/llama3.3-b_given_robust.pkl", "rb") as f:
    df_llama_robust = pickle.load(f)
with open("data/analysis/llama3.3-b_given_siebert.pkl", "rb") as f:
    df_llama_siebert = pickle.load(f)
with open("data/analysis/llama3.3-b_given_bert-base-multilingual.pkl", "rb") as f:
    df_llama_bert_base = pickle.load(f)
df_llama = df_llama_robust.join(df_llama_siebert['siebert']).join(df_llama_bert_base['bert-base'])
df_llama['siebert'] = df_llama['siebert'].apply(lambda x: x[0]['label'])

# Sentiment

### GPT-4o mini

In [4]:
counts = df_gpt['robust_sentiment'].value_counts()
counts_m = df_gpt[df_gpt['profile_id'].isin(male_profiles)]['robust_sentiment'].value_counts()
counts_f = df_gpt[df_gpt['profile_id'].isin(female_profiles)]['robust_sentiment'].value_counts()

pd.DataFrame({
    # 'total'  : counts,
    # 'males'  : counts_m,
    # 'females': counts_f,
    'total_%'  : round(counts.div(counts.sum(), axis=0)*100,1),
    'males_%'  : round(counts_m.div(counts_m.sum(), axis=0)*100,1),
    'females_%': round(counts_f.div(counts_f.sum(), axis=0)*100,1)
})

                  total_%  males_%  females_%
robust_sentiment
Neutral              85.2     88.8       81.5
Positive             13.0     10.2       15.8
Very Positive         1.6      0.6        2.6
Negative              0.2      0.4        0.1
Very Negative         0.0      0.0        0.0

In [5]:
counts = df_gpt['siebert'].value_counts()
counts_m = df_gpt[df_gpt['profile_id'].isin(male_profiles)]['siebert'].value_counts()
counts_f = df_gpt[df_gpt['profile_id'].isin(female_profiles)]['siebert'].value_counts()

pd.DataFrame({
    # 'total'  : counts,
    # 'males'  : counts_m,
    # 'females': counts_f,
    'total_%'  : round(counts.div(counts.sum(), axis=0)*100,1),
    'males_%'  : round(counts_m.div(counts_m.sum(), axis=0)*100,1),
    'females_%': round(counts_f.div(counts_f.sum(), axis=0)*100,1)
})

          total_%  males_%  females_%
siebert
POSITIVE     99.1     98.6       99.7
NEGATIVE      0.9      1.4        0.3

In [6]:
counts = df_gpt['bert-base'].value_counts()
counts_m = df_gpt[df_gpt['profile_id'].isin(male_profiles)]['bert-base'].value_counts()
counts_f = df_gpt[df_gpt['profile_id'].isin(female_profiles)]['bert-base'].value_counts()

pd.DataFrame({
    # 'total'  : counts,
    # 'males'  : counts_m,
    # 'females': counts_f,
    'total_%'  : round(counts.div(counts.sum(), axis=0)*100,1),
    'males_%'  : round(counts_m.div(counts_m.sum(), axis=0)*100,1),
    'females_%': round(counts_f.div(counts_f.sum(), axis=0)*100,1)
})

           total_%  males_%  females_%
bert-base
4 stars       91.4     92.3       90.5
5 stars        7.0      5.7        8.4
2 stars        1.4      1.8        1.0
3 stars        0.2      0.2        0.1

### Llama 3.3

In [7]:
counts = df_llama['robust_sentiment'].value_counts()
counts_m = df_llama[df_llama['profile_id'].isin(male_profiles)]['robust_sentiment'].value_counts()
counts_f = df_llama[df_llama['profile_id'].isin(female_profiles)]['robust_sentiment'].value_counts()

pd.DataFrame({
    # 'total'  : counts,
    # 'males'  : counts_m,
    # 'females': counts_f,
    'total_%'  : round(counts.div(counts.sum(), axis=0)*100,2),
    'males_%'  : round(counts_m.div(counts_m.sum(), axis=0)*100,2),
    'females_%': round(counts_f.div(counts_f.sum(), axis=0)*100,2)
})

                  total_%  males_%  females_%
robust_sentiment
Neutral             70.31    75.27      65.30
Positive            25.52    21.51      29.58
Very Positive        3.09     1.71       4.48
Negative             0.78     1.00       0.56
Very Negative        0.30     0.51       0.09

In [8]:
counts = df_llama['siebert'].value_counts()
counts_m = df_llama[df_llama['profile_id'].isin(male_profiles)]['siebert'].value_counts()
counts_f = df_llama[df_llama['profile_id'].isin(female_profiles)]['siebert'].value_counts()

pd.DataFrame({
    # 'total'  : counts,
    # 'males'  : counts_m,
    # 'females': counts_f,
    'total_%'  : round(counts.div(counts.sum(), axis=0)*100,1),
    'males_%'  : round(counts_m.div(counts_m.sum(), axis=0)*100,1),
    'females_%': round(counts_f.div(counts_f.sum(), axis=0)*100,1)
})

          total_%  males_%  females_%
siebert
POSITIVE     99.9     99.8      100.0
NEGATIVE      0.1      0.2        0.0

In [9]:
counts = df_llama['bert-base'].value_counts()
counts_m = df_llama[df_llama['profile_id'].isin(male_profiles)]['bert-base'].value_counts()
counts_f = df_llama[df_llama['profile_id'].isin(female_profiles)]['bert-base'].value_counts()

pd.DataFrame({
    'total'  : counts,
    'males'  : counts_m,
    'females': counts_f,
    'total_%'  : round(counts.div(counts.sum(), axis=0)*100,1),
    'males_%'  : round(counts_m.div(counts_m.sum(), axis=0)*100,1),
    'females_%': round(counts_f.div(counts_f.sum(), axis=0)*100,1)
})
# more balanced ratings compared to gpt

           total  males  females  total_%  males_%  females_%
bert-base
4 stars    56900  28544    28299     89.8     90.3       89.3
5 stars     5678   2647     3030      9.0      8.4        9.6
3 stars      710    383      325      1.1      1.2        1.0
2 stars       72     46       26      0.1      0.1        0.1

# Disparity

In [10]:
SENTIMENT_MAPPINGS = {
    'robust_sentiment': {
        "Very Negative": 0,
        "Negative": 1,
        "Neutral": 2,
        "Positive": 3,
        "Very Positive": 4
    },
    'siebert': {
        "NEGATIVE": 0,
        "POSITIVE": 1
    },
    'bert-base': {
        "1 star" : 0,
        "2 stars": 1,
        "3 stars": 2,
        "4 stars": 3,
        "5 stars": 4
    }
}

In [11]:
def compute_sentiment_disparity(df, sentiment_classifier, sentiment_to_num):
    # first we map the categorical data to int values
    df['sentiment_score'] = df[sentiment_classifier].map(sentiment_to_num[sentiment_classifier])
    # then we aggregate by profile id
    profile_sentiment = df.groupby('profile_id')['sentiment_score'].agg('mean')

    pairs = []

    for i in range(1, 529):
        male_score = profile_sentiment.loc[i]
        female_score = profile_sentiment.loc[i + 528]
        diff = female_score - male_score  # positive means female received higher sentiment

        pairs.append({
            'profile_id_male': i,
            'profile_id_female': i + 528,
            'sentiment_male_score': male_score,
            'sentiment_female_score': female_score,
            'sentiment_score_diff': diff
        })

    return pd.DataFrame(pairs)

def sentiment_disparity_analsysis(disparity_df):
    mean_diff = disparity_df['sentiment_score_diff'].mean()
    std_diff = disparity_df['sentiment_score_diff'].std()
    direction_bias = disparity_df['sentiment_score_diff'].gt(0).mean()
    parity = (disparity_df['sentiment_score_diff'] == 0).mean()

    t_stat, p_val_t = ttest_rel(disparity_df['sentiment_female_score'], disparity_df['sentiment_male_score'])
    
    return mean_diff, std_diff, direction_bias, parity, t_stat, p_val_t

In [12]:
disparity_df = compute_sentiment_disparity(df_gpt, 'siebert', SENTIMENT_MAPPINGS)
print("Model: gpt | Sentiment classifier: SiEBERT")
print("------------------------------------------")
mean_diff, std_diff, direction_bias, parity, t_stat, p_val_t = sentiment_disparity_analsysis(disparity_df)
print(f"Mean difference: {mean_diff:.3f}")
print(f"Std deviation: {std_diff:.3f}")
print(f"Percentage of pairs where female score > male score: {direction_bias:.2%}")
print(f"Percentage of pairs where female score = male score: {parity:.2%}")
print(f"Paired t-test: t = {t_stat:.3f}, p = {p_val_t:.4f}")

Model: gpt | Sentiment classifier: SiEBERT
------------------------------------------
Mean difference: 0.011
Std deviation: 0.028
Percentage of pairs where female score > male score: 30.30%
Percentage of pairs where female score = male score: 66.48%
Paired t-test: t = 9.487, p = 0.0000

In [13]:
disparity_df = compute_sentiment_disparity(df_gpt, 'robust_sentiment', SENTIMENT_MAPPINGS)
print("Model: gpt | Sentiment classifier: Robust Sentiment")
print("------------------------------------------")
mean_diff, std_diff, direction_bias, parity, t_stat, p_val_t = sentiment_disparity_analsysis(disparity_df)
print(f"Mean difference: {mean_diff:.3f}")
print(f"Std deviation: {std_diff:.3f}")
print(f"Percentage of pairs where female score > male score: {direction_bias:.2%}")
print(f"Percentage of pairs where female score = male score: {parity:.2%}")
print(f"Paired t-test: t = {t_stat:.3f}, p = {p_val_t:.4f}")

Model: gpt | Sentiment classifier: Robust Sentiment
------------------------------------------
Mean difference: 0.099
Std deviation: 0.098
Percentage of pairs where female score > male score: 84.66%
Percentage of pairs where female score = male score: 4.36%
Paired t-test: t = 23.166, p = 0.0000

In [14]:
disparity_df = compute_sentiment_disparity(df_gpt, 'bert-base', SENTIMENT_MAPPINGS)
print("Model: gpt | Sentiment classifier: BERT base")
print("------------------------------------------")
mean_diff, std_diff, direction_bias, parity, t_stat, p_val_t = sentiment_disparity_analsysis(disparity_df)
print(f"Mean difference: {mean_diff:.3f}")
print(f"Std deviation: {std_diff:.3f}")
print(f"Percentage of pairs where female score > male score: {direction_bias:.2%}")
print(f"Percentage of pairs where female score = male score: {parity:.2%}")
print(f"Paired t-test: t = {t_stat:.3f}, p = {p_val_t:.4f}")

# TODO: double-check

Model: gpt | Sentiment classifier: BERT base
------------------------------------------
Mean difference: 0.042
Std deviation: 0.083
Percentage of pairs where female score > male score: 65.72%
Percentage of pairs where female score = male score: 7.39%
Paired t-test: t = 11.616, p = 0.0000

In [15]:
disparity_df = compute_sentiment_disparity(df_llama, 'siebert', SENTIMENT_MAPPINGS)
print("Model: llama | Sentiment classifier: SiEBERT")
print("------------------------------------------")
mean_diff, std_diff, direction_bias, parity, t_stat, p_val_t = sentiment_disparity_analsysis(disparity_df)
print(f"Mean difference: {mean_diff:.3f}")
print(f"Std deviation: {std_diff:.3f}")
print(f"Percentage of pairs where female score > male score: {direction_bias:.2%}")
print(f"Percentage of pairs where female score = male score: {parity:.2%}")
print(f"Paired t-test: t = {t_stat:.3f}, p = {p_val_t:.4f}")

Model: llama | Sentiment classifier: SiEBERT
------------------------------------------
Mean difference: 0.002
Std deviation: 0.022
Percentage of pairs where female score > male score: 2.27%
Percentage of pairs where female score = male score: 97.73%
Paired t-test: t = 2.406, p = 0.0165

In [16]:
disparity_df = compute_sentiment_disparity(df_llama, 'robust_sentiment', SENTIMENT_MAPPINGS)
print("Model: llama | Sentiment classifier: Robust Sentiment")
print("------------------------------------------")
mean_diff, std_diff, direction_bias, parity, t_stat, p_val_t = sentiment_disparity_analsysis(disparity_df)
print(f"Mean difference: {mean_diff:.3f}")
print(f"Std deviation: {std_diff:.3f}")
print(f"Percentage of pairs where female score > male score: {direction_bias:.2%}")
print(f"Percentage of pairs where female score = male score: {parity:.2%}")
print(f"Paired t-test: t = {t_stat:.3f}, p = {p_val_t:.4f}")

Model: llama | Sentiment classifier: Robust Sentiment
------------------------------------------
Mean difference: 0.151
Std deviation: 0.278
Percentage of pairs where female score > male score: 71.02%
Percentage of pairs where female score = male score: 2.27%
Paired t-test: t = 12.504, p = 0.0000

In [17]:
disparity_df = compute_sentiment_disparity(df_llama, 'bert-base', SENTIMENT_MAPPINGS)
print("Model: llama | Sentiment classifier: BERT base")
print("------------------------------------------")
mean_diff, std_diff, direction_bias, parity, t_stat, p_val_t = sentiment_disparity_analsysis(disparity_df)
print(f"Mean difference: {mean_diff:.3f}")
print(f"Std deviation: {std_diff:.3f}")
print(f"Percentage of pairs where female score > male score: {direction_bias:.2%}")
print(f"Percentage of pairs where female score = male score: {parity:.2%}")
print(f"Paired t-test: t = {t_stat:.3f}, p = {p_val_t:.4f}")

Model: llama | Sentiment classifier: BERT base
------------------------------------------
Mean difference: 0.015
Std deviation: 0.182
Percentage of pairs where female score > male score: 44.70%
Percentage of pairs where female score = male score: 15.53%
Paired t-test: t = 1.902, p = 0.0577